### PR TITLE
Update auth rules

### PR DESCRIPTION
**Pull request by WadeBarnes**
- Update reference links to CANdy Network Provisional Governance Framework (Layer 1) document.
- Update permissions for adding a NETWORK_MONITOR DID

### CODE REVIEW

**Comment by SylvainMartel** [comment]
@WadeBarnes I see the links now point to the Groupes-de-travail-CANdy-Working-Groups repo, but does the fact that it's a private repo cause problem?

**Comment by WadeBarnes** [comment]
> @WadeBarnes I see the links now point to the Groupes-de-travail-CANdy-Working-Groups repo, but does the fact that it's a private repo cause problem?

Great question @SylvainMartel.  @PhilippeBourque, @CharlesMacpherson, @krobinsonca, Would you be able to weigh in on the fact that the draft governance documents are now restricted access?  Is the plan to open it back up at some point?

**Comment by WadeBarnes** [comment]
Sounds good.  So we'll keep the reference links pointing to the private repo for now since that is the only reference.  We'll update to the public references when they become available.

**Comment by WadeBarnes** [comment]
The updated rules have been written to the ledgers.

**Review by CharlesMacpherson — APPROVED** [review]
LGTM

**Review by SylvainMartel — APPROVED** [review]

**Pull request merged**
