### PR TITLE
Add Archive/Restore playbooks and documentation

### PR DESCRIPTION
**Pull request by WadeBarnes**

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@donato-ods-devops, this PR contains the scripts we were discussing yesterday,

**Comment by WadeBarnes** [comment]
History on the PR is not looking correct.  I'll clean that up.

**Comment by SylvainMartel** [comment]
I should be able to take a look before wednesday

**Comment by WadeBarnes** [comment]
> I should be able to take a look before wednesday

This is just an interim PR.  There will be more updates to support the upgrade/migration following; separate PR(s).

**Review by SylvainMartel — APPROVED** [review]
LGTM

**Pull request merged**
